package hotel.view;

import hotel.model.Pessoa;
import hotel.model.Reserva;
import hotel.repository.PessoaRepository;
import hotel.repository.ReservaRepository;
import hotel.support.AutoFill;
import hotel.support.DocumentoLimitado;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

public class frmLocacao extends javax.swing.JInternalFrame {

    List<Pessoa> listAcompanhante;
    Pessoa pessoaTitular;

    public frmLocacao() {
        initComponents();
        listAcompanhante = new ArrayList<>();
        AutoFill autoFill = new AutoFill(new ArrayList<Reserva>(ReservaRepository.readAll()), tfdPesquisaReserva, pnlFields, pnlAcompanhante1);
        setFieldsEditable(false);
        this.tfdPessoaCodigo.setVisible(false);
        //new AutoFill(new ArrayList<Reserva>(ReservaRepository.readAll()), tfdPesquisaReserva, pnlFields, pnlAcompanhante1);
    }

    private void setFieldsEditable(boolean editable) {
        tfdValor.setEditable(editable);
        tfdCelular.setEditable(editable);
        tfdCodigo.setEditable(editable);
        tfdDataEntrada.setEditable(editable);
        tfdDataSaida.setEditable(editable);
        tfdNomeTitular.setEditable(editable);
        tfdQuarto.setEditable(editable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgPesquisa = new javax.swing.ButtonGroup();
        btgCadastro = new javax.swing.ButtonGroup();
        btgPesquisaReserva = new javax.swing.ButtonGroup();
        pnlHeader = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        tbpLocacao = new javax.swing.JTabbedPane();
        pnlCadastro = new javax.swing.JPanel();
        tbpCadastro = new javax.swing.JTabbedPane();
        pnlComReserva = new javax.swing.JPanel();
        pnlPesquisaReserva = new javax.swing.JPanel();
        rbnPesquisaReservaCPF = new javax.swing.JRadioButton();
        rbnPesquisaReservaNome = new javax.swing.JRadioButton();
        lblPesquisaReserva = new javax.swing.JLabel();
        tfdPesquisaReserva = new javax.swing.JTextField();
        pnlAcompanhante1 = new javax.swing.JPanel();
        scpAcompanhante1 = new javax.swing.JScrollPane();
        tbListaAcompanhante1 = new javax.swing.JTable();
        btnSelecaoPessoa = new javax.swing.JButton();
        pnlFields = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        tfdCodigo = new javax.swing.JTextField();
        tfdQuarto = new javax.swing.JTextField();
        lblQuarto = new javax.swing.JLabel();
        lblNomeTitular = new javax.swing.JLabel();
        lblDataNasc = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        tfdNomeTitular = new javax.swing.JTextField();
        tfdDataEntrada = new javax.swing.JTextField();
        tfdDataSaida = new javax.swing.JTextField();
        tfdCelular = new javax.swing.JTextField();
        tfdValor = new hotel.support.JNumberFormatField();
        tfdPessoaCodigo = new javax.swing.JTextField();
        pnlSemReserva = new javax.swing.JPanel();
        pnlListagem = new javax.swing.JPanel();
        pnlDetalhe = new javax.swing.JPanel();
        tfdPesquisa = new javax.swing.JTextField();
        lblPesquisa = new javax.swing.JLabel();
        pnlOpcao = new javax.swing.JPanel();
        rbNome = new javax.swing.JRadioButton();
        rbCodigo = new javax.swing.JRadioButton();
        btnPesquisa = new javax.swing.JButton();
        scpLista = new javax.swing.JScrollPane();
        tblLista = new javax.swing.JTable();

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(12, 91, 160));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/images/save.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(12, 91, 160));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/images/edit.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(12, 91, 160));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/images/trash.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnFechar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFechar.setForeground(new java.awt.Color(12, 91, 160));
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/images/close.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFechar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFechar)
                .addContainerGap())
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalvar)
            .addComponent(btnEditar)
            .addComponent(btnExcluir)
            .addComponent(btnFechar)
        );

        tbpLocacao.setBackground(new java.awt.Color(255, 255, 255));
        tbpLocacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbpLocacao.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tbpLocacaoStateChanged(evt);
            }
        });

        pnlCadastro.setBackground(new java.awt.Color(255, 255, 255));
        pnlCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Cadastro de Locação ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tbpCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        pnlComReserva.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        pnlPesquisaReserva.setBackground(new java.awt.Color(255, 255, 255));
        pnlPesquisaReserva.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Pesquisar Reserva ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 15))); // NOI18N

        rbnPesquisaReservaCPF.setBackground(new java.awt.Color(255, 255, 255));
        btgPesquisaReserva.add(rbnPesquisaReservaCPF);
        rbnPesquisaReservaCPF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbnPesquisaReservaCPF.setText("CPF do Titular");
        rbnPesquisaReservaCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnPesquisaReservaCPFActionPerformed(evt);
            }
        });

        rbnPesquisaReservaNome.setBackground(new java.awt.Color(255, 255, 255));
        btgPesquisaReserva.add(rbnPesquisaReservaNome);
        rbnPesquisaReservaNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbnPesquisaReservaNome.setSelected(true);
        rbnPesquisaReservaNome.setText("Nome do Titular");
        rbnPesquisaReservaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnPesquisaReservaNomeActionPerformed(evt);
            }
        });

        lblPesquisaReserva.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPesquisaReserva.setForeground(new java.awt.Color(102, 102, 102));
        lblPesquisaReserva.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPesquisaReserva.setText("<html>Nome<font color='red'><b>*</b></font>:</html>");
        lblPesquisaReserva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tfdPesquisaReserva.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tfdPesquisaReserva.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        tfdPesquisaReserva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfdPesquisaReservaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlPesquisaReservaLayout = new javax.swing.GroupLayout(pnlPesquisaReserva);
        pnlPesquisaReserva.setLayout(pnlPesquisaReservaLayout);
        pnlPesquisaReservaLayout.setHorizontalGroup(
            pnlPesquisaReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPesquisaReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPesquisaReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPesquisaReservaLayout.createSequentialGroup()
                        .addComponent(rbnPesquisaReservaNome)
                        .addGap(18, 18, 18)
                        .addComponent(rbnPesquisaReservaCPF)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlPesquisaReservaLayout.createSequentialGroup()
                        .addComponent(lblPesquisaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfdPesquisaReserva)))
                .addContainerGap())
        );
        pnlPesquisaReservaLayout.setVerticalGroup(
            pnlPesquisaReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPesquisaReservaLayout.createSequentialGroup()
                .addGroup(pnlPesquisaReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbnPesquisaReservaNome)
                    .addComponent(rbnPesquisaReservaCPF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPesquisaReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdPesquisaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnlAcompanhante1.setBackground(new java.awt.Color(255, 255, 255));
        pnlAcompanhante1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acompanhantes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 15))); // NOI18N

        scpAcompanhante1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 15))); // NOI18N

        tbListaAcompanhante1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF", "E-mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scpAcompanhante1.setViewportView(tbListaAcompanhante1);

        btnSelecaoPessoa.setBackground(new java.awt.Color(12, 91, 160));
        btnSelecaoPessoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSelecaoPessoa.setForeground(new java.awt.Color(255, 255, 255));
        btnSelecaoPessoa.setText("Selecionar acompanhantes");
        btnSelecaoPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecaoPessoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAcompanhante1Layout = new javax.swing.GroupLayout(pnlAcompanhante1);
        pnlAcompanhante1.setLayout(pnlAcompanhante1Layout);
        pnlAcompanhante1Layout.setHorizontalGroup(
            pnlAcompanhante1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAcompanhante1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpAcompanhante1, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlAcompanhante1Layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(btnSelecaoPessoa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAcompanhante1Layout.setVerticalGroup(
            pnlAcompanhante1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAcompanhante1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(btnSelecaoPessoa)
                .addGap(18, 18, 18)
                .addComponent(scpAcompanhante1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlFields.setBackground(new java.awt.Color(255, 255, 255));
        pnlFields.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados da Reserva", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 15))); // NOI18N

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(102, 102, 102));
        lblCodigo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCodigo.setText("<html>Código<font color='red'><b>*</b></font>:</html>");
        lblCodigo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tfdCodigo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tfdCodigo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        tfdCodigo.setName("tfdCodigo"); // NOI18N

        tfdQuarto.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tfdQuarto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        tfdQuarto.setName("tfdQuarto"); // NOI18N
        tfdQuarto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfdQuartoTyped(evt);
            }
        });

        lblQuarto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblQuarto.setForeground(new java.awt.Color(102, 102, 102));
        lblQuarto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblQuarto.setText("<html>Quarto<font color='red'><b>*</b></font>:</html>");
        lblQuarto.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblNomeTitular.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNomeTitular.setForeground(new java.awt.Color(102, 102, 102));
        lblNomeTitular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNomeTitular.setText("<html>Nome titular<font color='red'><b>*</b></font>:</html>");

        lblDataNasc.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDataNasc.setForeground(new java.awt.Color(102, 102, 102));
        lblDataNasc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDataNasc.setText("<html>Data entrada<font color='red'><b>*</b></font>:</html>");
        lblDataNasc.setToolTipText("");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(102, 102, 102));
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmail.setText("<html>Data saída<font color='red'><b></b></font>:</html>");

        lblTelefone.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTelefone.setForeground(new java.awt.Color(102, 102, 102));
        lblTelefone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelefone.setText("<html>Valor<font color='red'><b>*</b></font>:</html>");

        lblCelular.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblCelular.setForeground(new java.awt.Color(102, 102, 102));
        lblCelular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCelular.setText("<html>Celular<font color='red'><b>*</b></font>:</html>");

        tfdNomeTitular.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tfdNomeTitular.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        tfdNomeTitular.setName("tfdNomeTitular"); // NOI18N

        tfdDataEntrada.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tfdDataEntrada.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        tfdDataEntrada.setName("tfdDataEntrada"); // NOI18N

        tfdDataSaida.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tfdDataSaida.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        tfdDataSaida.setName("tfdDataSaida"); // NOI18N

        tfdCelular.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tfdCelular.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        tfdCelular.setName("tfdCelular"); // NOI18N

        tfdValor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        tfdValor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfdValor.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tfdValor.setName("tfdValor"); // NOI18N

        tfdPessoaCodigo.setName("tfdPessoaCodigo"); // NOI18N

        javax.swing.GroupLayout pnlFieldsLayout = new javax.swing.GroupLayout(pnlFields);
        pnlFields.setLayout(pnlFieldsLayout);
        pnlFieldsLayout.setHorizontalGroup(
            pnlFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFieldsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfdPessoaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(pnlFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail)
                    .addComponent(lblDataNasc, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(lblNomeTitular)
                    .addComponent(lblQuarto)
                    .addComponent(lblCodigo)
                    .addComponent(lblTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfdCelular)
                    .addGroup(pnlFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tfdQuarto, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                        .addComponent(tfdNomeTitular)
                        .addComponent(tfdDataEntrada, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfdDataSaida, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfdCodigo, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(tfdValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlFieldsLayout.setVerticalGroup(
            pnlFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFieldsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfdQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFieldsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdNomeTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlFieldsLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(tfdPessoaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(133, 133, 133))
        );

        javax.swing.GroupLayout pnlComReservaLayout = new javax.swing.GroupLayout(pnlComReserva);
        pnlComReserva.setLayout(pnlComReservaLayout);
        pnlComReservaLayout.setHorizontalGroup(
            pnlComReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlComReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPesquisaReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAcompanhante1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlComReservaLayout.setVerticalGroup(
            pnlComReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComReservaLayout.createSequentialGroup()
                .addComponent(pnlPesquisaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAcompanhante1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFields, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tbpCadastro.addTab("Com Reserva", pnlComReserva);

        javax.swing.GroupLayout pnlSemReservaLayout = new javax.swing.GroupLayout(pnlSemReserva);
        pnlSemReserva.setLayout(pnlSemReservaLayout);
        pnlSemReservaLayout.setHorizontalGroup(
            pnlSemReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlSemReservaLayout.setVerticalGroup(
            pnlSemReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tbpCadastro.addTab("Sem Reserva", pnlSemReserva);

        javax.swing.GroupLayout pnlCadastroLayout = new javax.swing.GroupLayout(pnlCadastro);
        pnlCadastro.setLayout(pnlCadastroLayout);
        pnlCadastroLayout.setHorizontalGroup(
            pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbpCadastro)
                .addContainerGap())
        );
        pnlCadastroLayout.setVerticalGroup(
            pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpCadastro)
        );

        tbpLocacao.addTab("Adicionar", pnlCadastro);

        pnlListagem.setBackground(new java.awt.Color(255, 255, 255));

        pnlDetalhe.setBackground(new java.awt.Color(255, 255, 255));

        tfdPesquisa.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tfdPesquisa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        tfdPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfdPesquisaKeyTyped(evt);
            }
        });

        lblPesquisa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPesquisa.setText("Nome:");

        pnlOpcao.setBackground(new java.awt.Color(255, 255, 255));
        pnlOpcao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Pesquisa Detalhada ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        rbNome.setBackground(new java.awt.Color(255, 255, 255));
        btgPesquisa.add(rbNome);
        rbNome.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        rbNome.setSelected(true);
        rbNome.setText("Por nome");
        rbNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNomeActionPerformed(evt);
            }
        });

        rbCodigo.setBackground(new java.awt.Color(255, 255, 255));
        btgPesquisa.add(rbCodigo);
        rbCodigo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        rbCodigo.setText("Por código");
        rbCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOpcaoLayout = new javax.swing.GroupLayout(pnlOpcao);
        pnlOpcao.setLayout(pnlOpcaoLayout);
        pnlOpcaoLayout.setHorizontalGroup(
            pnlOpcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbCodigo))
        );
        pnlOpcaoLayout.setVerticalGroup(
            pnlOpcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOpcaoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlOpcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbNome)
                    .addComponent(rbCodigo))
                .addContainerGap())
        );

        btnPesquisa.setBackground(new java.awt.Color(12, 91, 160));
        btnPesquisa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPesquisa.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisa.setText("Pesquisar");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDetalheLayout = new javax.swing.GroupLayout(pnlDetalhe);
        pnlDetalhe.setLayout(pnlDetalheLayout);
        pnlDetalheLayout.setHorizontalGroup(
            pnlDetalheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalheLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetalheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlOpcao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPesquisa)
                    .addComponent(tfdPesquisa))
                .addGap(18, 18, 18)
                .addComponent(btnPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 511, Short.MAX_VALUE))
        );
        pnlDetalheLayout.setVerticalGroup(
            pnlDetalheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalheLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOpcao, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetalheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisa))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        tblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "CPF", "CNPJ"
            }
        ));
        scpLista.setViewportView(tblLista);

        javax.swing.GroupLayout pnlListagemLayout = new javax.swing.GroupLayout(pnlListagem);
        pnlListagem.setLayout(pnlListagemLayout);
        pnlListagemLayout.setHorizontalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDetalhe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scpLista)))
                .addContainerGap())
        );
        pnlListagemLayout.setVerticalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDetalhe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpLista, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbpLocacao.addTab("Listagem", pnlListagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbpLocacao))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbpLocacao)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
//        if (Validacao.validarCampos(pnlCadastro) == 0) {
//            if (Validacao.validarCPF(Formatacao.removerFormatacao(tfdCPF.getText()))) {
//                if (Validacao.validarDataFormatada(tfdDataNasc.getText())) {
//                    if (Validacao.validarEmail(tfdEmail.getText())) {
//                        boolean isNew = (pessoa.getCodPessoa() == null);
//
//                        pessoa.setNomPessoa(tfdQuarto.getText());
//                        pessoa.setDesEmail(tfdEmail.getText());
//                        pessoa.setDesEndereco(tfdRua.getText() + "," + tfdNumero.getText() + "," + tfdComplemento.getText());
//                        Date dataNasc = Date.valueOf(Formatacao.ajustaDataAMD(tfdDataNasc.getText()));
//                        pessoa.setDtaNasc(dataNasc);
//                        pessoa.setNumCelular(Formatacao.removerFormatacao(tfdCelular.getText().replace(" ", "")));
//                        pessoa.setNumCpf(Formatacao.removerFormatacao(tfdCPF.getText()));
//                        pessoa.setNumTelefone(Formatacao.removerFormatacao(tfdTelefone.getText().replace(" ", "")));
//                        pessoa.setIndSituacao("A");
//                        pessoaController.save(pessoa);
//
//                        if (!isNew) {
//                            JOptionPane.showMessageDialog(this, "Atualizado com sucesso!");
//                            setVisibleCodigo(false);
//                        } else {
//                            JOptionPane.showMessageDialog(this, "Cadastrado com sucesso!");
//                        }
//
//                        pessoaController.popularTabela(tblLista, 0, "");
//
//                        limparCampos();
//                        setAba(1);
//                    } else {
//                        JOptionPane.showMessageDialog(this, "E-mail inválido!");
//                    }
//                } else {
//                    JOptionPane.showMessageDialog(this, "Data inválida!");
//                }
//            } else {
//                JOptionPane.showMessageDialog(this, "CPF inválido!");
//            }
//        } else {
//            JOptionPane.showMessageDialog(this, "Campos obrigatórios não preenchidos!");
//        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
//        pessoa = pessoaController.getReadId(Integer.parseInt(tblLista.getModel().getValueAt(tblLista.getSelectedRow(), 0).toString()));
//        popularTelaCadastro();
//        setAba(0);
//        tfdQuarto.requestFocus();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
//        Object[] options = {"Sim", "Não"};
//        int escolha = JOptionPane.showOptionDialog(null, "Você tem certeza que gostaria de excluir o registro " + tblLista.getModel().getValueAt(tblLista.getSelectedRow(), 0).toString() + "?", "Escolha", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
//        if (escolha == 0) {
//            pessoaController.changeSituation(Integer.parseInt(tblLista.getModel().getValueAt(tblLista.getSelectedRow(), 0).toString()));
//            JOptionPane.showMessageDialog(this, "Excluído com sucesso!");
//            pessoaController.popularTabela(tblLista, 0, "");
//        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void tfdQuartoTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdQuartoTyped
        char vChar = evt.getKeyChar();
        if (!(Character.isLetter(vChar) || (vChar == KeyEvent.VK_BACK_SPACE) || (vChar == KeyEvent.VK_DELETE) || (vChar == KeyEvent.VK_SPACE))) {
            evt.consume();
        }
    }//GEN-LAST:event_tfdQuartoTyped

    private void tfdPesquisaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdPesquisaKeyTyped
        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar) || (vChar == KeyEvent.VK_BACK_SPACE) || (vChar == KeyEvent.VK_DELETE))) {
            if (rbCodigo.isSelected()) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_tfdPesquisaKeyTyped

    private void rbNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNomeActionPerformed
        lblPesquisa.setText("Nome:");
        tfdPesquisa.setText("");
    }//GEN-LAST:event_rbNomeActionPerformed

    private void rbCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCodigoActionPerformed
        lblPesquisa.setText("Código:");
        tfdPesquisa.setText("");
    }//GEN-LAST:event_rbCodigoActionPerformed

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
//        if (tfdPesquisa.getText().trim().isEmpty()) {
//            pessoaController.popularTabela(tblLista, 0, "");
//        } else if (rbNome.isSelected()) {
//            pessoaController.popularTabela(tblLista, 1, tfdPesquisa.getText());
//        } else if (rbCodigo.isSelected()) {
//            pessoaController.popularTabela(tblLista, 2, tfdPesquisa.getText());
//        }
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void tbpLocacaoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tbpLocacaoStateChanged
//        habilitar();
    }//GEN-LAST:event_tbpLocacaoStateChanged

    private void rbnPesquisaReservaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnPesquisaReservaNomeActionPerformed
        lblPesquisaReserva.setText("<html>Nome<font color='red'><b>*</b></font>:</html>");
        tfdPesquisaReserva.setDocument(new DocumentoLimitado(200));
        AutoFill autoFill = new AutoFill(new ArrayList<Reserva>(ReservaRepository.readAll()), tfdPesquisaReserva, pnlFields, pnlAcompanhante1);
    }//GEN-LAST:event_rbnPesquisaReservaNomeActionPerformed

    private void rbnPesquisaReservaCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnPesquisaReservaCPFActionPerformed
        lblPesquisaReserva.setText("<html>CPF<font color='red'><b>*</b></font>:</html>");
        tfdPesquisaReserva.setDocument(new DocumentoLimitado(11));
        AutoFill autoFill = new AutoFill(new ArrayList<Reserva>(ReservaRepository.readAll()), tfdPesquisaReserva, pnlFields, pnlAcompanhante1);
    }//GEN-LAST:event_rbnPesquisaReservaCPFActionPerformed

    private void btnSelecaoPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecaoPessoaActionPerformed
        pessoaTitular = PessoaRepository.readId(Integer.parseInt(tfdPessoaCodigo.getText()));
        frmPrincipal principal = (frmPrincipal) ((JFrame) SwingUtilities.getWindowAncestor(this));
        frmSelecaoPessoa pessoa = new frmSelecaoPessoa(tbListaAcompanhante1, listAcompanhante, pessoaTitular);
        principal.abrirTela(pessoa);
    }//GEN-LAST:event_btnSelecaoPessoaActionPerformed

    private void tfdPesquisaReservaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdPesquisaReservaKeyTyped
        char vChar = evt.getKeyChar();
        if (rbnPesquisaReservaNome.isSelected()) {
            if (!(Character.isLetter(vChar) || (vChar == KeyEvent.VK_BACK_SPACE) || (vChar == KeyEvent.VK_DELETE))) {
                evt.consume();
            }
        } else if (rbnPesquisaReservaCPF.isSelected()) {
            if (!(Character.isDigit(vChar) || (vChar == KeyEvent.VK_BACK_SPACE) || (vChar == KeyEvent.VK_DELETE))) {
                evt.consume();
            }
        } 
    }//GEN-LAST:event_tfdPesquisaReservaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgCadastro;
    private javax.swing.ButtonGroup btgPesquisa;
    private javax.swing.ButtonGroup btgPesquisaReserva;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSelecaoPessoa;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDataNasc;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNomeTitular;
    private javax.swing.JLabel lblPesquisa;
    private javax.swing.JLabel lblPesquisaReserva;
    private javax.swing.JLabel lblQuarto;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JPanel pnlAcompanhante1;
    private javax.swing.JPanel pnlCadastro;
    private javax.swing.JPanel pnlComReserva;
    private javax.swing.JPanel pnlDetalhe;
    private javax.swing.JPanel pnlFields;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlListagem;
    private javax.swing.JPanel pnlOpcao;
    private javax.swing.JPanel pnlPesquisaReserva;
    private javax.swing.JPanel pnlSemReserva;
    private javax.swing.JRadioButton rbCodigo;
    private javax.swing.JRadioButton rbNome;
    private javax.swing.JRadioButton rbnPesquisaReservaCPF;
    private javax.swing.JRadioButton rbnPesquisaReservaNome;
    private javax.swing.JScrollPane scpAcompanhante1;
    private javax.swing.JScrollPane scpLista;
    private javax.swing.JTable tbListaAcompanhante1;
    private javax.swing.JTable tblLista;
    private javax.swing.JTabbedPane tbpCadastro;
    private javax.swing.JTabbedPane tbpLocacao;
    private javax.swing.JTextField tfdCelular;
    private javax.swing.JTextField tfdCodigo;
    private javax.swing.JTextField tfdDataEntrada;
    private javax.swing.JTextField tfdDataSaida;
    private javax.swing.JTextField tfdNomeTitular;
    private javax.swing.JTextField tfdPesquisa;
    private javax.swing.JTextField tfdPesquisaReserva;
    private javax.swing.JTextField tfdPessoaCodigo;
    private javax.swing.JTextField tfdQuarto;
    private hotel.support.JNumberFormatField tfdValor;
    // End of variables declaration//GEN-END:variables
}
