package hotel.view;

import hotel.controller.ReservaController;
import hotel.model.Reserva;
import hotel.repository.ReservaRepository;
import hotel.support.DocumentoLimitado;
import hotel.support.Formatacao;
import hotel.support.Validacao;
import java.awt.Component;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

public class frmSelecaoReserva extends javax.swing.JDialog {

    Reserva reserva;
    ReservaController reservaController;
    JPanel pnlFields;

    public frmSelecaoReserva(java.awt.Frame parent, boolean modal, JPanel fields) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.reserva = new Reserva();
        this.reservaController = new ReservaController();
        this.pnlFields = fields;
        reservaController.popularTabela(tblListaBusca, 3, "");
    }

    private void comparaFields(JTextField field) {
        if (field.getName().equals("tfdCodigo")) {
            field.setText(reserva.getCodReserva().toString());
        } else if (field.getName().equals("tfdQuarto")) {
            field.setText(reserva.getCodQuarto().getCodQuarto().toString());
        } else if (field.getName().equals("tfdNomeTitular")) {
            field.setText(reserva.getCodPessoa().getNomPessoa());
        } else if (field.getName().equals("tfdDataEntrada")) {
            field.setText(Formatacao.ajustaDataDMAH(reserva.getDtaEntrada().toString()));
        } else if (field.getName().equals("tfdDataSaida")) {
            field.setText(Formatacao.ajustaDataDMAH(reserva.getDtaSaida().toString()));
        } else if (field.getName().equals("tfdValor")) {
            field.setText(reserva.getVlrReserva().toString());
        } else if (field.getName().equals("tfdCelular")) {
            field.setText(reserva.getCodPessoa().getNumCelular());
        } else if (field.getName().equals("tfdPessoaCodigo")) {
            field.setText(reserva.getCodPessoa().getCodPessoa().toString());
        }
    }

    public Reserva getReserva() {
        return reserva;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgPesquisa = new javax.swing.ButtonGroup();
        pnlHeader = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pnlPesquisaReserva = new javax.swing.JPanel();
        rbnPesquisaReservaCPF = new javax.swing.JRadioButton();
        rbnPesquisaReservaNome = new javax.swing.JRadioButton();
        lblPesquisaReserva = new javax.swing.JLabel();
        tfdPesquisaReserva = new javax.swing.JTextField();
        btnPesquisa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        scpLista = new javax.swing.JScrollPane();
        tblListaBusca = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(12, 91, 160));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/images/tap.png"))); // NOI18N
        btnSalvar.setText("Selecionar");
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnFechar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFechar.setForeground(new java.awt.Color(12, 91, 160));
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/images/close.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFechar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFechar)
                .addContainerGap())
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalvar)
            .addComponent(btnFechar)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pnlPesquisaReserva.setBackground(new java.awt.Color(255, 255, 255));
        pnlPesquisaReserva.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Pesquisar Reserva ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 15))); // NOI18N

        rbnPesquisaReservaCPF.setBackground(new java.awt.Color(255, 255, 255));
        btgPesquisa.add(rbnPesquisaReservaCPF);
        rbnPesquisaReservaCPF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbnPesquisaReservaCPF.setText("CPF do Titular");
        rbnPesquisaReservaCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnPesquisaReservaCPFActionPerformed(evt);
            }
        });

        rbnPesquisaReservaNome.setBackground(new java.awt.Color(255, 255, 255));
        btgPesquisa.add(rbnPesquisaReservaNome);
        rbnPesquisaReservaNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbnPesquisaReservaNome.setSelected(true);
        rbnPesquisaReservaNome.setText("Nome do Titular");
        rbnPesquisaReservaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnPesquisaReservaNomeActionPerformed(evt);
            }
        });

        lblPesquisaReserva.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPesquisaReserva.setForeground(new java.awt.Color(102, 102, 102));
        lblPesquisaReserva.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPesquisaReserva.setText("<html>Nome<font color='red'><b>*</b></font>:</html>");
        lblPesquisaReserva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tfdPesquisaReserva.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tfdPesquisaReserva.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        tfdPesquisaReserva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfdPesquisaReservaKeyTyped(evt);
            }
        });

        btnPesquisa.setBackground(new java.awt.Color(12, 91, 160));
        btnPesquisa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPesquisa.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisa.setText("Pesquisar");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPesquisaReservaLayout = new javax.swing.GroupLayout(pnlPesquisaReserva);
        pnlPesquisaReserva.setLayout(pnlPesquisaReservaLayout);
        pnlPesquisaReservaLayout.setHorizontalGroup(
            pnlPesquisaReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPesquisaReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPesquisaReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPesquisaReservaLayout.createSequentialGroup()
                        .addComponent(rbnPesquisaReservaNome)
                        .addGap(18, 18, 18)
                        .addComponent(rbnPesquisaReservaCPF))
                    .addGroup(pnlPesquisaReservaLayout.createSequentialGroup()
                        .addComponent(lblPesquisaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfdPesquisaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisa)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        pnlPesquisaReservaLayout.setVerticalGroup(
            pnlPesquisaReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPesquisaReservaLayout.createSequentialGroup()
                .addGroup(pnlPesquisaReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbnPesquisaReservaNome)
                    .addComponent(rbnPesquisaReservaCPF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPesquisaReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdPesquisaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisa))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setText("Resultado busca");

        tblListaBusca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "CPF", "CNPJ"
            }
        ));
        scpLista.setViewportView(tblListaBusca);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPesquisaReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scpLista, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPesquisaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpLista, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (tblListaBusca.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Você não selecionou nenhuma reserva!");
        } else {
            reserva = ReservaRepository.readId(Integer.parseInt(tblListaBusca.getModel().getValueAt(tblListaBusca.getSelectedRow(), 0).toString()));
            this.dispose();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        reserva = null;
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void rbnPesquisaReservaCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnPesquisaReservaCPFActionPerformed
        lblPesquisaReserva.setText("<html>CPF<font color='red'><b>*</b></font>:</html>");
        tfdPesquisaReserva.setDocument(new DocumentoLimitado(11));
    }//GEN-LAST:event_rbnPesquisaReservaCPFActionPerformed

    private void rbnPesquisaReservaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnPesquisaReservaNomeActionPerformed
        lblPesquisaReserva.setText("<html>Nome<font color='red'><b>*</b></font>:</html>");
        tfdPesquisaReserva.setDocument(new DocumentoLimitado(200));
    }//GEN-LAST:event_rbnPesquisaReservaNomeActionPerformed

    private void tfdPesquisaReservaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdPesquisaReservaKeyTyped
        char vChar = evt.getKeyChar();
        if (rbnPesquisaReservaNome.isSelected()) {
            if (!(Character.isLetter(vChar) || (vChar == KeyEvent.VK_BACK_SPACE) || (vChar == KeyEvent.VK_DELETE))) {
                evt.consume();
            }
        } else if (rbnPesquisaReservaCPF.isSelected()) {
            if (!(Character.isDigit(vChar) || (vChar == KeyEvent.VK_BACK_SPACE) || (vChar == KeyEvent.VK_DELETE))) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_tfdPesquisaReservaKeyTyped

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        if (tfdPesquisaReserva.getText().trim().isEmpty()) {
            reservaController.popularTabela(tblListaBusca, 3, "");
        } else if (rbnPesquisaReservaNome.isSelected()) {
            reservaController.popularTabela(tblListaBusca, 1, tfdPesquisaReserva.getText());
        } else if (rbnPesquisaReservaCPF.isSelected()) {
            reservaController.popularTabela(tblListaBusca, 2, tfdPesquisaReserva.getText());
        }
    }//GEN-LAST:event_btnPesquisaActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgPesquisa;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPesquisaReserva;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlPesquisaReserva;
    private javax.swing.JRadioButton rbnPesquisaReservaCPF;
    private javax.swing.JRadioButton rbnPesquisaReservaNome;
    private javax.swing.JScrollPane scpLista;
    private javax.swing.JTable tblListaBusca;
    private javax.swing.JTextField tfdPesquisaReserva;
    // End of variables declaration//GEN-END:variables
}
