package hotel.view;

import hotel.controller.PessoaController;
import hotel.model.Pessoa;
import hotel.repository.PessoaRepository;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;

public class frmSelecaoPessoa extends javax.swing.JDialog {

    Pessoa pessoa, pessoaTitular;
    PessoaController pessoaController;
    List<Pessoa> listPessoas;
    JTable tblAcomp;

    public frmSelecaoPessoa(java.awt.Frame parent, boolean modal, JTable tblAcomp, List<Pessoa> listPessoas, Pessoa pessoaTitular) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        pessoa = new Pessoa();
        this.pessoaTitular = pessoaTitular;
        pessoaController = new PessoaController();
        this.listPessoas = listPessoas;
        this.tblAcomp = tblAcomp;
        pessoaController.popularTabela(tblListaBusca, 3, "A", this.pessoaTitular.getCodPessoa());
        btnAdicionar.setEnabled(false);
        btnRemover.setEnabled(false);

        tfdPesquisa.requestFocus();

        tblListaBusca.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            if (tblListaBusca.getSelectedRow() != -1) {
                btnAdicionar.setEnabled(true);
                tblListaAcompanhante.clearSelection();
            } else {
                btnAdicionar.setEnabled(false);
            }
        });

        tblListaAcompanhante.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
            if (tblListaAcompanhante.getSelectedRow() != -1) {
                btnRemover.setEnabled(true);
                tblListaBusca.clearSelection();
            } else {
                btnRemover.setEnabled(false);
            }
        });
        if (tblAcomp.getModel().getRowCount() == -1) {
            clearTabela(tblListaAcompanhante);
        } else {
            tblListaAcompanhante.setModel(this.tblAcomp.getModel());
        }
    }

    public frmSelecaoPessoa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        pessoa = new Pessoa();
        lblAcompanhantes.setText("Pessoa titular");
        pessoaController = new PessoaController();
        pessoaController.popularTabela(tblListaBusca, 3, "A", -1);
        btnAdicionar.setEnabled(false);
        btnRemover.setEnabled(false);

        tfdPesquisa.requestFocus();

        tblListaBusca.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            if ((tblListaBusca.getSelectedRow() != -1) && (tblListaAcompanhante.getModel().getRowCount() == 0)) {
                btnAdicionar.setEnabled(true);
                tblListaAcompanhante.clearSelection();
            } else {
                btnAdicionar.setEnabled(false);
            }
        });

        tblListaAcompanhante.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
            if (tblListaAcompanhante.getSelectedRow() != -1) {
                btnAdicionar.setEnabled(false);
                btnRemover.setEnabled(true);
                tblListaBusca.clearSelection();
            } else {
                btnRemover.setEnabled(false);
            }
        });
        
        clearTabela(tblListaAcompanhante);
    }

    public List<Pessoa> getListPessoas() {
        return listPessoas;
    }

    public Pessoa getPessoaTitular() {
        return pessoaTitular;
    }

    private void clearTabela(JTable tblTable) {
        DefaultTableModel modelAcompanhante = (DefaultTableModel) tblTable.getModel();
        modelAcompanhante.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgPesquisa = new javax.swing.ButtonGroup();
        pnlListagem = new javax.swing.JPanel();
        pnlDetalhe = new javax.swing.JPanel();
        tfdPesquisa = new javax.swing.JTextField();
        lblPesquisa = new javax.swing.JLabel();
        pnlOpcao = new javax.swing.JPanel();
        rbNome = new javax.swing.JRadioButton();
        rbCPF = new javax.swing.JRadioButton();
        btnAdicionarPessoa = new javax.swing.JButton();
        lblOU = new javax.swing.JLabel();
        btnPesquisa = new javax.swing.JButton();
        scpLista = new javax.swing.JScrollPane();
        tblListaBusca = new javax.swing.JTable();
        lblBusca = new javax.swing.JLabel();
        lblAcompanhantes = new javax.swing.JLabel();
        scpLista1 = new javax.swing.JScrollPane();
        tblListaAcompanhante = new javax.swing.JTable();
        pnlHeader = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlListagem.setBackground(new java.awt.Color(255, 255, 255));

        pnlDetalhe.setBackground(new java.awt.Color(255, 255, 255));

        tfdPesquisa.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tfdPesquisa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        tfdPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfdPesquisaKeyTyped(evt);
            }
        });

        lblPesquisa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPesquisa.setText("Nome:");

        pnlOpcao.setBackground(new java.awt.Color(255, 255, 255));
        pnlOpcao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Pesquisa Detalhada ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        rbNome.setBackground(new java.awt.Color(255, 255, 255));
        btgPesquisa.add(rbNome);
        rbNome.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        rbNome.setSelected(true);
        rbNome.setText("Por nome");
        rbNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNomeActionPerformed(evt);
            }
        });

        rbCPF.setBackground(new java.awt.Color(255, 255, 255));
        btgPesquisa.add(rbCPF);
        rbCPF.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        rbCPF.setText("Por CPF");
        rbCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCPFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOpcaoLayout = new javax.swing.GroupLayout(pnlOpcao);
        pnlOpcao.setLayout(pnlOpcaoLayout);
        pnlOpcaoLayout.setHorizontalGroup(
            pnlOpcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbCPF))
        );
        pnlOpcaoLayout.setVerticalGroup(
            pnlOpcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOpcaoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlOpcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbNome)
                    .addComponent(rbCPF))
                .addContainerGap())
        );

        btnAdicionarPessoa.setBackground(new java.awt.Color(12, 91, 160));
        btnAdicionarPessoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdicionarPessoa.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionarPessoa.setText("Adicionar");
        btnAdicionarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarPessoaActionPerformed(evt);
            }
        });

        lblOU.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblOU.setText("OU");

        btnPesquisa.setBackground(new java.awt.Color(12, 91, 160));
        btnPesquisa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPesquisa.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisa.setText("Pesquisar");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDetalheLayout = new javax.swing.GroupLayout(pnlDetalhe);
        pnlDetalhe.setLayout(pnlDetalheLayout);
        pnlDetalheLayout.setHorizontalGroup(
            pnlDetalheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalheLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOpcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfdPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdicionarPessoa)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlDetalheLayout.setVerticalGroup(
            pnlDetalheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalheLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDetalheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisa)
                    .addComponent(tfdPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisa)
                    .addComponent(lblOU)
                    .addComponent(btnAdicionarPessoa))
                .addGap(44, 44, 44))
            .addGroup(pnlDetalheLayout.createSequentialGroup()
                .addComponent(pnlOpcao, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tblListaBusca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "CPF", "CNPJ"
            }
        ));
        scpLista.setViewportView(tblListaBusca);

        lblBusca.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblBusca.setText("Resultado busca");

        lblAcompanhantes.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblAcompanhantes.setText("Acompanhantes");

        tblListaAcompanhante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "CPF", "E-mail"
            }
        ));
        scpLista1.setViewportView(tblListaAcompanhante);

        javax.swing.GroupLayout pnlListagemLayout = new javax.swing.GroupLayout(pnlListagem);
        pnlListagem.setLayout(pnlListagemLayout);
        pnlListagemLayout.setHorizontalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDetalhe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scpLista, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scpLista1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlListagemLayout.createSequentialGroup()
                                .addComponent(lblAcompanhantes, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlListagemLayout.setVerticalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDetalhe, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBusca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scpLista, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(lblAcompanhantes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpLista1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(12, 91, 160));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/images/save.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdicionar.setForeground(new java.awt.Color(12, 91, 160));
        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/images/edit.png"))); // NOI18N
        btnAdicionar.setText("Adicionar ");
        btnAdicionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnRemover.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRemover.setForeground(new java.awt.Color(12, 91, 160));
        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/images/trash.png"))); // NOI18N
        btnRemover.setText("Remover");
        btnRemover.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRemover.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnFechar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFechar.setForeground(new java.awt.Color(12, 91, 160));
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/images/close.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFechar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 443, Short.MAX_VALUE)
                .addComponent(btnFechar)
                .addContainerGap())
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalvar)
            .addComponent(btnAdicionar)
            .addComponent(btnRemover)
            .addComponent(btnFechar)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlListagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlListagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (listPessoas != null) {
            if (listPessoas.isEmpty()) {
                JOptionPane.showMessageDialog(this, "A lista de acompanhantes está vazia!");
            } else {
                this.dispose();
            }
        } else {
            if (this.pessoaTitular == null) {
                JOptionPane.showMessageDialog(this, "Você não selecionou nenhuma pessoa como titular!");
            } else {
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        pessoa = pessoaController.getReadId(Integer.parseInt(tblListaBusca.getModel().getValueAt(tblListaBusca.getSelectedRow(), 0).toString()));
        if (listPessoas != null) {
            boolean pessoaOnList = false;
            for (Pessoa p : listPessoas) {
                if (p.getCodPessoa() == pessoa.getCodPessoa()) {
                    JOptionPane.showMessageDialog(this, "Você já adicinou essa pessoa aos acompanhantes!");
                    pessoaOnList = true;
                }
            }
            if (!pessoaOnList) {
                listPessoas.add(pessoa);
                clearTabela(tblListaAcompanhante);
                DefaultTableModel model = (DefaultTableModel) tblListaAcompanhante.getModel();
                for (Pessoa p : listPessoas) {
                    model.addRow(new Object[]{p.getCodPessoa(), p.getNomPessoa(), p.getNumCpf(), p.getDesEmail()});
                }
                tfdPesquisa.requestFocus();
            }
        } else {
            clearTabela(tblListaAcompanhante);
            DefaultTableModel model = (DefaultTableModel) tblListaAcompanhante.getModel();
            model.addRow(new Object[]{pessoa.getCodPessoa(), pessoa.getNomPessoa(), pessoa.getNumCpf(), pessoa.getDesEmail()});
            pessoaTitular = PessoaRepository.readId(pessoa.getCodPessoa());
            tfdPesquisa.requestFocus();
        }
        tblListaBusca.clearSelection();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        if(listPessoas != null) {
            listPessoas = null;
            clearTabela(tblAcomp);
        } else {
            pessoaTitular = null;
        }
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnAdicionarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarPessoaActionPerformed
        frmPrincipal principal = (frmPrincipal) ((JFrame) SwingUtilities.getWindowAncestor(this));
        frmPessoa frmPessoa = new frmPessoa();
        principal.abrirTela(frmPessoa);
    }//GEN-LAST:event_btnAdicionarPessoaActionPerformed

    private void rbCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCPFActionPerformed
        lblPesquisa.setText("CPF:");
        tfdPesquisa.setText("");
    }//GEN-LAST:event_rbCPFActionPerformed

    private void rbNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNomeActionPerformed
        lblPesquisa.setText("Nome:");
        tfdPesquisa.setText("");
    }//GEN-LAST:event_rbNomeActionPerformed

    private void tfdPesquisaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdPesquisaKeyTyped
        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar) || (vChar == KeyEvent.VK_BACK_SPACE) || (vChar == KeyEvent.VK_DELETE))) {
            if (rbCPF.isSelected()) {
                evt.consume();
            }
        } else if ((Character.isDigit(vChar) || (vChar == KeyEvent.VK_BACK_SPACE) || (vChar == KeyEvent.VK_DELETE))) {
            if (rbNome.isSelected()) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_tfdPesquisaKeyTyped

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        if (listPessoas != null) {
            DefaultTableModel model = (DefaultTableModel) tblListaAcompanhante.getModel();
            pessoa = pessoaController.getReadId(Integer.parseInt(tblListaAcompanhante.getModel().getValueAt(tblListaAcompanhante.getSelectedRow(), 0).toString()));
            clearTabela(tblListaAcompanhante);
            if (listPessoas.contains(pessoa)) {
                listPessoas.remove(pessoa);
            }

            for (Pessoa p : listPessoas) {
                model.addRow(new Object[]{p.getCodPessoa(), p.getNomPessoa(), p.getNumCpf(), p.getDesEmail()});
            }
        } else {
            DefaultTableModel model = (DefaultTableModel) tblListaAcompanhante.getModel();
            this.pessoaTitular = null;
            pessoa = pessoaController.getReadId(Integer.parseInt(tblListaAcompanhante.getModel().getValueAt(tblListaAcompanhante.getSelectedRow(), 0).toString()));
            clearTabela(tblListaAcompanhante);
        }
        tfdPesquisa.requestFocus();
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        if (listPessoas != null) {
            if (tfdPesquisa.getText().trim().isEmpty()) {
                pessoaController.popularTabela(tblListaBusca, 0, "", pessoaTitular.getCodPessoa());
            } else if (rbNome.isSelected()) {
                pessoaController.popularTabela(tblListaBusca, 1, tfdPesquisa.getText(), pessoaTitular.getCodPessoa());
            } else if (rbCPF.isSelected()) {
                pessoaController.popularTabela(tblListaBusca, 4, tfdPesquisa.getText(), pessoaTitular.getCodPessoa());
            }
        } else {
            if (tfdPesquisa.getText().trim().isEmpty()) {
                pessoaController.popularTabela(tblListaBusca, 0, "", -1);
            } else if (rbNome.isSelected()) {
                pessoaController.popularTabela(tblListaBusca, 1, tfdPesquisa.getText(), -1);
            } else if (rbCPF.isSelected()) {
                pessoaController.popularTabela(tblListaBusca, 4, tfdPesquisa.getText(), -1);
            }
        }
    }//GEN-LAST:event_btnPesquisaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgPesquisa;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAdicionarPessoa;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblAcompanhantes;
    private javax.swing.JLabel lblBusca;
    private javax.swing.JLabel lblOU;
    private javax.swing.JLabel lblPesquisa;
    private javax.swing.JPanel pnlDetalhe;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlListagem;
    private javax.swing.JPanel pnlOpcao;
    private javax.swing.JRadioButton rbCPF;
    private javax.swing.JRadioButton rbNome;
    private javax.swing.JScrollPane scpLista;
    private javax.swing.JScrollPane scpLista1;
    private javax.swing.JTable tblListaAcompanhante;
    private javax.swing.JTable tblListaBusca;
    private javax.swing.JTextField tfdPesquisa;
    // End of variables declaration//GEN-END:variables
}
